behaviors:
  ParallelPark:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 7
      learning_rate: 6.5e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 3
      vis_encode_type: simple
      memory:
        memory_size: 64
        sequence_length: 64
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.1
        gamma: 0.99
    keep_checkpoints: 2
    max_steps: 2.0e6
    time_horizon: 256
    summary_freq: 25000
    threaded: true
