behaviors:
  ParallelPark:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate: 8.0e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.3
        gamma: 0.99
    keep_checkpoints: 5
    max_steps: 1.0e7
    time_horizon: 1024
    summary_freq: 20000
    threaded: true
