behaviors:
  ParallelPark:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.3
        gamma: 0.99
      gail:
        strength: 0.5
        demo_path: Demonstrations/Parking1.demo
    keep_checkpoints: 5
    max_steps: 2.0e6
    time_horizon: 1000
    summary_freq: 10000
